### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by msoos** [shawn-ogg/maxapp_linux_installer#2]
Not an issue, just a short note of thanks! Really helped, I was having trouble making the Windows one work on Linux.

Cheers and keep up the good work,

Mate

PS: I had to adjust to make it work on Arch Linux, it was a bit messy. But worked :)

**Comment by shawn-ogg** [comment]
Thanks for this "issue" :+1: 
Feel free to send me the arch modifications.

**Comment by david-woelfle** [comment]
I do absolutely agree, great work thank you! You saved by day today :)
